/nobackup/fsjsk/cylinder/surfaces_and_fields/system_cylinder.py:102: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  Kthth_integral, error = integrate.quad(lambda z: self.Kthth_integrand(amplitude, z),  0, 2 * math.pi / self.wavenumber)
/nobackup/fsjsk/cylinder/surfaces_and_fields/system_cylinder.py:102: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  Kthth_integral, error = integrate.quad(lambda z: self.Kthth_integrand(amplitude, z),  0, 2 * math.pi / self.wavenumber)
/nobackup/fsjsk/cylinder/surfaces_and_fields/system_cylinder.py:102: IntegrationWarning: The algorithm does not converge.  Roundoff error is detected
  in the extrapolation table.  It is assumed that the requested tolerance
  cannot be achieved, and that the returned result (if full_output = 1) is 
  the best which can be obtained.
  Kthth_integral, error = integrate.quad(lambda z: self.Kthth_integrand(amplitude, z),  0, 2 * math.pi / self.wavenumber)
Traceback (most recent call last):
  File "run_lattice.py", line 187, in <module>
    run_experiment(loop_type,  range1, range2)
  File "run_lattice.py", line 119, in run_experiment
    results = loop(functions_dict[exp_type], range1, range2)
  File "run_lattice.py", line 34, in loop
    amplitude_avg, field_avg = single_run_lambda(var1, var2) 
  File "run_lattice.py", line 54, in <lambda>
    wavenumber=var_wvn, intrinsic_curvature = intrinsic_curvature),                   
  File "run_lattice.py", line 90, in single_run
    lattice.measure()
  File "/nobackup/fsjsk/cylinder/surfaces_and_fields/On_lattice_simple.py", line 81, in measure
    assert(self.amplitude_average <1)
AssertionError
